/* Shared planner: Supabase is the sole source of planner content and photos. */
const MONTHS = [['September',2026,8],['October',2026,9],['November',2026,10],['December',2026,11],['January',2027,0],['February',2027,1],['March',2027,2],['April',2027,3],['May',2027,4],['June',2027,5],['July',2027,6],['August',2027,7]];
const MONTH_NAMES = MONTHS.map(([name,year,month]) => ({name,year,month}));
const MAX_WEEKLY_IMAGES = 4;
const cfg = window.PLANNER_SUPABASE_CONFIG || {};
const configured = Boolean(window.supabase && cfg.url && cfg.anonKey && !cfg.url.includes('YOUR_') && !cfg.anonKey.includes('YOUR_') && !cfg.anonKey.includes('PASTE_'));
const db = configured ? window.supabase.createClient(cfg.url, cfg.anonKey) : null;
const bucket = cfg.storageBucket || 'planner-photos';
const app = document.getElementById('app'), toast = document.getElementById('toast');
let route = {page:'home',monthIndex:0,weekIndex:0}, planner = blankPlanner(), editor = false, loading = false, loginOpen = false, loginBusy = false;
let loadError = configured ? '' : 'The administrator has not connected the shared planner yet.';
let toastTimer; const saveTimers = new Map();

function defaultObjective(m,w) { return ['Welcome students, set up teams, and introduce the engineering design process.','Explore sensors and simple inputs through a guided investigation.','Plan, build, test, and improve a first working robot prototype.','Document results, reflect on the build, and share discoveries.'][w % 4] || `Develop the ${MONTH_NAMES[m].name} robotics learning sequence.`; }
function createWeek(m,w) { const x=MONTH_NAMES[m], start=mondayForWeek(x.year,x.month,w), end=new Date(start); end.setDate(end.getDate()+4); return {id:null,objective:defaultObjective(m,w),classDetails:w===0?'Mini lesson: safety, materials, and the week’s challenge.\nStudio time: build in pairs and test one idea.':'Mini lesson and design prompt.\nCollaborative build, test, and quick share-out.',project:w===0?'First build challenge':'Prototype iteration',notes:'',images:[],start:dateKey(start),end:dateKey(end)}; }
function blankPlanner() { return {months:MONTH_NAMES.map((_,m)=>({weeks:Array.from({length:4},(_,w)=>createWeek(m,w))}))}; }
function icon(n) { return {grid:'<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/></svg>',arrow:'<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg>',back:'<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 12H5M11 18l-6-6 6-6"/></svg>',print:'<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M7 8V3h10v5M6 17H4V9h16v8h-2M7 14h10v7H7z"/></svg>',calendar:'<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></svg>'}[n] || ''; }
function say(msg) { clearTimeout(toastTimer); toast.textContent=msg; toast.classList.add('show'); toastTimer=setTimeout(()=>toast.classList.remove('show'),2600); }
function notice() { return loading?'<div class="backend-notice">Connecting to the shared planner…</div>':loadError?`<div class="backend-notice is-error">${escapeHTML(loadError)}</div>`:''; }
function access() { if(!configured)return '<span class="access-pill muted">SETUP REQUIRED</span>'; return editor?'<span class="access-pill editor">EDITOR MODE</span><button class="button button-secondary button-small" type="button" data-action="sign-out">SIGN OUT</button>':'<button class="button button-secondary button-small" type="button" data-action="admin-login">ADMIN LOGIN</button>'; }
function modal() { return loginOpen?`<div class="auth-overlay"><section class="auth-card glass" role="dialog" aria-modal="true" aria-labelledby="login-title"><button class="modal-close" type="button" data-action="close-login" aria-label="Close login">×</button><p class="eyebrow">Administrator access</p><h2 id="login-title">ADMIN LOGIN</h2><p>Only the account granted administrator permission can make changes.</p><form id="admin-login-form"><label>Email<input name="email" type="email" autocomplete="username" inputmode="email" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="button button-primary" type="submit" ${loginBusy?'disabled':''}>${loginBusy?'SIGNING IN…':'SIGN IN'}</button></form></section></div>`:''; }
function layout(content,float=true) { return `<header class="topbar"><button class="brand" type="button" data-action="home"><span class="mark">${icon('grid')}</span><span class="brand-copy"><span class="brand-name">ROBOTICS CLASS</span><span class="brand-subtitle">SCHEDULE &amp; OBJECTIVES</span></span></button><div class="top-actions"><button class="button button-secondary button-small print-control" type="button" data-action="print">${icon('print')} PRINT / EXPORT</button>${access()}<button class="icon-button" type="button" data-action="year" aria-label="Open year plan">${icon('calendar')}</button></div></header>${content}${float?`<button class="floating-weekly" type="button" data-action="weekly">${icon('calendar')} WEEKLY SCHEDULE</button>`:''}${modal()}`; }

function renderHome() { app.innerHTML=layout(`<section class="glass panel home-panel"><div class="hero-copy"><p class="eyebrow">2026 / 2027 planner</p><h1>ROBOTICS<br><span>CLASS.</span></h1><p class="hero-description">A calm, flexible home for every class plan, weekly objective, build challenge, and studio note.</p><div class="meta-row"><span><i class="dot"></i><strong>NOAH R</strong> — Teacher</span><span>September 2026 — August 2027</span></div>${notice()}</div><div class="home-bottom"><p class="fine-print">${editor?'You are authenticated as the planner editor. Changes are saved to the shared planner.':'Viewing the shared planner. Only the authenticated administrator can change its content.'}</p><button class="button button-primary" type="button" data-action="year">YEAR PLAN ${icon('arrow')}</button></div></section>`,false); }
function renderYear() { const cards=MONTH_NAMES.map((m,i)=>`<button class="month-card" type="button" data-month="${i}"><span class="month-number">${String(i+1).padStart(2,'0')}</span><span class="month-name">${m.name}</span><span class="month-year">${m.year}</span><span class="month-weeks">${planner.months[i].weeks.length} WEEKS</span><span class="month-arrow">→</span></button>`).join(''); app.innerHTML=layout(`<section class="glass panel view-panel"><div class="view-head"><div><p class="eyebrow">Academic year</p><h1 class="view-title">YEAR PLAN</h1><p class="view-subtitle">September 2026 — August 2027 · Select a month to plan the studio weeks.</p>${notice()}</div><button class="nav-back" type="button" data-action="home">${icon('back')} HOME</button></div><div class="year-statbar"><div class="stat-card"><span class="stat-label">Class</span><span class="stat-value">Robotics Class</span></div><div class="stat-card"><span class="stat-label">Teacher</span><span class="stat-value">Noah R</span></div><div class="stat-card"><span class="stat-label">Access</span><span class="stat-value">${editor?'Editor':'View only'}</span></div></div><div class="months-grid">${cards}</div></section>`); }
function viewField(label,value,empty) { return `<div class="viewer-field"><span class="month-field-label">${label}</span><p>${lineBreaks(value||empty)}</p></div>`; }
function renderMonth(mi) { const month=MONTH_NAMES[mi], weeks=planner.months[mi].weeks.map((w,wi)=>{const dates=weekDates(w.start).map((d,i)=>`<span class="date-chip ${i>4?'is-weekend':''}">${shortDate(d)}</span>`).join(''); const fields=editor?`<label class="week-field-group"><span class="month-field-label">Weekly objective</span><textarea class="month-field" data-month-field="objective" data-week-index="${wi}">${escapeHTML(w.objective)}</textarea></label><label class="week-field-group"><span class="month-field-label">Class / schedule</span><textarea class="month-field" data-month-field="classDetails" data-week-index="${wi}">${escapeHTML(w.classDetails)}</textarea></label>`:`${viewField('Weekly objective',w.objective,'No weekly objective has been published.')}${viewField('Class / schedule',w.classDetails,'No class schedule has been published.')}`; return `<article class="week-card"><div class="week-index">WEEK ${String(wi+1).padStart(2,'0')}<span class="week-date">${range(w.start,w.end)}</span><span class="week-project">${escapeHTML(w.project||'Untitled build')}${w.images.length?` · ${w.images.length} PHOTO${w.images.length===1?'':'S'}`:''}</span></div><span class="week-dates">${dates}</span>${fields}<button class="week-detail-button" type="button" data-week="${wi}">OPEN <span>→</span></button></article>`;}).join(''); app.innerHTML=layout(`<section class="glass panel view-panel"><div class="view-head"><div><p class="eyebrow">Monthly studio plan</p><h1 class="view-title">${month.name.toUpperCase()}</h1><p class="view-subtitle">${month.year} · ${editor?'Edit the monthly plan or open a week for more detail.':'Browse published objectives and class plans.'}</p></div><button class="nav-back" type="button" data-action="year">${icon('back')} YEAR PLAN</button></div><div class="month-toolbar"><p class="date-range">${month.name.toUpperCase()} ${month.year} · ${planner.months[mi].weeks.length} WEEKLY PLANS</p>${editor?'<button class="button button-secondary button-small" type="button" data-action="add-week">+ ADD WEEK</button>':''}</div><div class="week-list">${weeks}</div></section>`); if(editor) bindMonth(mi); }
function gallery(images) { if(!images.length)return '<div class="photo-empty"><span class="photo-empty-icon">✦</span><span>No project photos have been published for this week.</span></div>'; return images.map((x,i)=>`<figure class="photo-tile"><img src="${x.src}" alt="${escapeHTML(x.name||'Weekly project photo')}">${editor?`<button class="photo-remove" type="button" data-remove-image="${i}" aria-label="Remove photo">×</button>`:''}<figcaption>${escapeHTML(x.name||`Photo ${i+1}`)}</figcaption></figure>`).join(''); }
function readCard(label,value,empty) { return `<section class="form-card"><span class="form-label">${label}</span><p class="read-only-text">${lineBreaks(value||empty)}</p></section>`; }
function renderWeek(mi,wi) { const month=MONTH_NAMES[mi], w=planner.months[mi].weeks[wi], dates=weekDates(w.start).slice(0,5).map(d=>`<span class="date-chip">${shortDate(d)}</span>`).join(''); const edit=`<div><section class="form-card"><label class="form-label" for="objective">Weekly objective</label><textarea id="objective" class="editable objective-field" data-field="objective">${escapeHTML(w.objective)}</textarea><p class="field-note">Changes save to the shared planner after you pause typing.</p></section><section class="form-card"><label class="form-label" for="classDetails">Class / schedule</label><textarea id="classDetails" class="editable" data-field="classDetails">${escapeHTML(w.classDetails)}</textarea></section></div><div><section class="form-card"><label class="form-label" for="project">Build / project</label><input id="project" class="editable" data-field="project" value="${escapeHTML(w.project)}"></section><section class="form-card"><label class="form-label" for="notes">Teacher notes</label><textarea id="notes" class="editable" data-field="notes">${escapeHTML(w.notes)}</textarea></section></div>`; const view=`<div>${readCard('Weekly objective',w.objective,'No weekly objective has been published.')}${readCard('Class / schedule',w.classDetails,'No class details have been published.')}</div><div>${readCard('Build / project',w.project,'No build has been published.')}${readCard('Teacher notes',w.notes,'No teacher notes have been published.')}</div>`; app.innerHTML=layout(`<section class="glass panel view-panel"><div class="view-head detail-head"><div><p class="eyebrow">${month.name} ${month.year}</p><h1 class="view-title">WEEK ${String(wi+1).padStart(2,'0')}</h1><div class="weekly-dates">${dates}</div></div><div><button class="nav-back" type="button" data-action="month">${icon('back')} ${month.name.toUpperCase()}</button><p class="save-status" id="save-status">${editor?'SHARED EDITOR MODE':'VIEW ONLY'}</p></div></div><div class="detail-layout">${editor?edit:view}</div><section class="form-card photo-card"><div class="photo-card-head"><div><span class="form-label">Project photos</span><p class="field-note">A visual record of prototypes, testing, and student work.</p></div>${editor?'<label class="photo-upload" for="week-images">+ ADD PHOTOS<input id="week-images" type="file" accept="image/*" multiple></label>':''}</div><div class="photo-gallery">${gallery(w.images)}</div></section></section>`); if(editor) bindWeek(mi,wi); }
function render() { if(route.page==='home')renderHome(); else if(route.page==='year')renderYear(); else if(route.page==='month')renderMonth(route.monthIndex); else renderWeek(route.monthIndex,route.weekIndex); }
function nav(next) { route={...route,...next}; render(); window.scrollTo({top:0,behavior:'smooth'}); }
function bindMonth(mi) { document.querySelectorAll('[data-month-field]').forEach(f=>f.addEventListener('input',e=>{const wi=+e.target.dataset.weekIndex; planner.months[mi].weeks[wi][e.target.dataset.monthField]=e.target.value; queueSave(mi,wi);})); }
function bindWeek(mi,wi) { document.querySelectorAll('[data-field]').forEach(f=>f.addEventListener('input',e=>{planner.months[mi].weeks[wi][e.target.dataset.field]=e.target.value; queueSave(mi,wi);})); const input=document.getElementById('week-images'); if(input)input.addEventListener('change',e=>{addImages(mi,wi,[...e.target.files]);e.target.value='';}); }
function queueSave(mi,wi) { const key=`${mi}-${wi}`; clearTimeout(saveTimers.get(key)); const s=document.getElementById('save-status'); if(s)s.textContent='SAVING…'; saveTimers.set(key,setTimeout(()=>saveWeek(mi,wi),550)); }
async function saveWeek(mi,wi) { if(!editor)return; const w=planner.months[mi].weeks[wi], row={month_index:mi,week_index:wi,objective:w.objective,class_details:w.classDetails,project:w.project,notes:w.notes,start_date:w.start,end_date:w.end}; const r=await db.from('planner_weeks').upsert(row,{onConflict:'month_index,week_index'}).select('id').single(); if(r.error)return say(`Could not save: ${r.error.message}`); w.id=r.data.id; const s=document.getElementById('save-status'); if(s)s.textContent='SAVED TO SHARED PLANNER'; }
async function addImages(mi,wi,files) { const w=planner.months[mi].weeks[wi], list=files.filter(f=>f.type.startsWith('image/')).slice(0,MAX_WEEKLY_IMAGES-w.images.length); if(!list.length)return say(`Each week can hold up to ${MAX_WEEKLY_IMAGES} photos.`); try { for(const file of list){const blob=await compress(file), path=`weeks/${mi}/${wi}/${uid()}.jpg`, upload=await db.storage.from(bucket).upload(path,blob,{contentType:'image/jpeg'}); if(upload.error)throw upload.error; const saved=await db.from('planner_images').insert({month_index:mi,week_index:wi,storage_path:path,file_name:file.name||'Project photo',sort_order:w.images.length}).select().single(); if(saved.error){await db.storage.from(bucket).remove([path]);throw saved.error;} w.images.push({id:saved.data.id,path,name:saved.data.file_name,src:db.storage.from(bucket).getPublicUrl(path).data.publicUrl}); } renderWeek(mi,wi);say('Photo added to the shared planner.'); }catch(e){say(`Photo upload failed: ${e.message||'please try again'}`);} }
function compress(file) { return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{try{const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=c.getContext('2d');if(!ctx)throw Error('Canvas unavailable');ctx.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>b?resolve(b):reject(Error('Image compression failed')),'image/jpeg',.82);}catch(e){reject(e);}};img.src=r.result;};r.readAsDataURL(file);}); }
async function removeImage(i) { const w=planner.months[route.monthIndex].weeks[route.weekIndex], x=w.images[i]; if(!x||!editor)return; const d=await db.from('planner_images').delete().eq('id',x.id);if(d.error)return say(`Could not remove photo: ${d.error.message}`);const rm=await db.storage.from(bucket).remove([x.path]);if(rm.error)say('Photo hidden, but its file could not be removed.');w.images.splice(i,1);renderWeek(route.monthIndex,route.weekIndex); }
async function bootstrapPlanner() { if(!editor)return;const existing=await db.from('planner_weeks').select('id').limit(1);if(existing.error||existing.data.length)return;const seed=blankPlanner().months.flatMap((m,mi)=>m.weeks.map((w,wi)=>({month_index:mi,week_index:wi,objective:w.objective,class_details:w.classDetails,project:w.project,notes:w.notes,start_date:w.start,end_date:w.end})));const created=await db.from('planner_weeks').upsert(seed,{onConflict:'month_index,week_index'});if(created.error)say(`Could not publish the initial planner: ${created.error.message}`);}
async function loadShared() { if(!db)return;loading=true;loadError='';render();const [a,b]=await Promise.all([db.from('planner_weeks').select('*').order('month_index').order('week_index'),db.from('planner_images').select('*').order('sort_order')]);loading=false;if(a.error||b.error){loadError=`The shared planner could not load. ${a.error?.message||b.error?.message||''}`;render();return;}planner=blankPlanner();a.data.forEach(r=>{const month=planner.months[r.month_index];if(!month)return;while(month.weeks.length<=r.week_index)month.weeks.push(createWeek(r.month_index,month.weeks.length));const w=month.weeks[r.week_index];Object.assign(w,{id:r.id,objective:r.objective,classDetails:r.class_details,project:r.project,notes:r.notes,start:r.start_date,end:r.end_date});});b.data.forEach(r=>{const month=planner.months[r.month_index];if(!month)return;while(month.weeks.length<=r.week_index)month.weeks.push(createWeek(r.month_index,month.weeks.length));month.weeks[r.week_index].images.push({id:r.id,path:r.storage_path,name:r.file_name,src:db.storage.from(bucket).getPublicUrl(r.storage_path).data.publicUrl});});render(); }
async function checkEditor() { if(!db)return;const s=await db.auth.getSession();if(!s.data.session){editor=false;return;}const r=await db.rpc('is_admin');editor=!r.error&&r.data===true;if(!editor){await db.auth.signOut();say('This account is not authorized to edit the planner.');} }
async function signIn(form) { loginBusy=true;render();const r=await db.auth.signInWithPassword({email:form.elements.email.value.trim(),password:form.elements.password.value});loginBusy=false;if(r.error){say(`Login failed: ${r.error.message}`);render();return;}await checkEditor();if(editor){await bootstrapPlanner();await loadShared();}loginOpen=false;render();say(editor?'Editor mode enabled.':'This account is not authorized.'); }
function uid(){return window.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;}
app.addEventListener('click',async e=>{const a=e.target.closest('[data-action]');if(a){const x=a.dataset.action;if(x==='home')nav({page:'home'});else if(x==='year')nav({page:'year'});else if(x==='month')nav({page:'month'});else if(x==='weekly')nav({page:'week'});else if(x==='print')window.print();else if(x==='admin-login'){loginOpen=true;render();}else if(x==='close-login'){loginOpen=false;render();}else if(x==='sign-out'){await db.auth.signOut();editor=false;render();say('Signed out. You are now viewing the planner.');}else if(x==='add-week'&&editor){const weeks=planner.months[route.monthIndex].weeks;if(weeks.length>=6)say('This month already has six weekly plans.');else{weeks.push(createWeek(route.monthIndex,weeks.length));await saveWeek(route.monthIndex,weeks.length-1);renderMonth(route.monthIndex);}}return;}const remove=e.target.closest('[data-remove-image]');if(remove)return removeImage(+remove.dataset.removeImage);const m=e.target.closest('[data-month]');if(m)nav({page:'month',monthIndex:+m.dataset.month});const w=e.target.closest('[data-week]');if(w)nav({page:'week',weekIndex:+w.dataset.week});});
app.addEventListener('submit',e=>{if(e.target.id==='admin-login-form'){e.preventDefault();signIn(e.target);}});
function mondayForWeek(y,m,w){const first=new Date(y,m,1),d=new Date(first);d.setDate(1-((first.getDay()+6)%7)+w*7);return d;}function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}function parseDate(x){return new Date(`${x}T12:00:00`);}function weekDates(start){const d=parseDate(start);return Array.from({length:7},(_,i)=>{const n=new Date(d);n.setDate(n.getDate()+i);return n;});}function shortDate(d){return new Intl.DateTimeFormat('en',{weekday:'short',day:'numeric'}).format(d);}function range(a,b){const o={month:'short',day:'numeric'};return `${new Intl.DateTimeFormat('en',o).format(parseDate(a))}–${new Intl.DateTimeFormat('en',o).format(parseDate(b))}`;}function escapeHTML(x=''){return String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}function lineBreaks(x){return escapeHTML(x).replace(/\n/g,'<br>');}
async function initialize(){renderHome();if(!db)return;await checkEditor();await bootstrapPlanner();await loadShared();db.channel('planner-updates').on('postgres_changes',{event:'*',schema:'public',table:'planner_weeks'},loadShared).on('postgres_changes',{event:'*',schema:'public',table:'planner_images'},loadShared).subscribe();}initialize();
